languge : generic
sudo : required 
services :
    - docker

before_install :
    - docker build -t regevguy:docker-practice -f Dockerfile.dev .

script :
    - docker run -e CI=true regevguy:docker-practice npm run test

deploy : 
    provider : elasticbeanstalk
    region : "us-east-2"
    app : "docker-practice2"
    environment : "DockerPractice2-env"
    bucket_name : "elasticbeanstalk-us-east-2-205366435539"
    bucket_path : "docker-practice"
    on: 
        branch : master
        access_key_id :
            secure: $AWS_ACCESS_KEY
        secret_access_key :
            secure: $AWS_SECRET_KEY